
import type { Technology } from '../interfaces/Technology'
import {
  SiDocker,
  SiDotnet,
  SiFastapi,
  SiGithub,
  SiNodedotjs,
  SiPostgresql,
  SiPython,
  SiReact,
  SiSharp,
  SiTypescript,
} from 'react-icons/si'
const technologiesData: Technology[] = [
  {
    name: 'React',
    category: 'Frontend',
    icon: SiReact,
    x: 0.10,
    y: 0.16,
    size: 'primary',
  },
  {
    name: 'Python',
    category: 'Backend & IA',
    icon: SiPython,
    x: 0.90,
    y: 0.18,
    size: 'primary',
  },
  {
    name: 'Node.js',
    category: 'Backend',
    icon: SiNodedotjs,
    x: 0.94,
    y: 0.48,
    size: 'primary',
  },
  {
    name: 'FastAPI',
    category: 'Backend',
    icon: SiFastapi,
    x: 0.84,
    y: 0.82,
    size: 'primary',
  },
  {
    name: '.NET',
    category: 'Backend',
    icon: SiDotnet,
    x: 0.17,
    y: 0.83,
    size: 'primary',
  },
  {
    name: 'C#',
    category: 'Backend',
    icon: SiSharp,
    x: 0.06,
    y: 0.48,
    size: 'primary',
  },

  {
    name: 'TypeScript',
    category: 'Frontend',
    icon: SiTypescript,
    x: 0.31,
    y: 0.08,
    size: 'secondary',
  },
  {
    name: 'PostgreSQL',
    category: 'Base de datos',
    icon: SiPostgresql,
    x: 0.69,
    y: 0.09,
    size: 'secondary',
  },
  {
    name: 'Docker',
    category: 'Infraestructura',
    icon: SiDocker,
    x: 0.66,
    y: 0.91,
    size: 'secondary',
  },
  {
    name: 'n8n',
    category: 'Automatización',
    wordmark: 'n8n',
    x: 0.36,
    y: 0.91,
    size: 'secondary',
  },
  {
    name: 'GitHub',
    category: 'Desarrollo',
    icon: SiGithub,
    x: 0.09,
    y: 0.69,
    size: 'secondary',
  },
  {
    name: 'Power BI',
    category: 'Datos & Analytics',
    wordmark: 'PBI',
    x: 0.91,
    y: 0.69,
    size: 'secondary',
  },
]

export { technologiesData }