
import type { Technology } from '../interfaces/Technology'
import powerAutomateLogo from '../assets/power-automate.svg'
import { DiMsqlServer } from 'react-icons/di'
import { TbBrandCSharp } from 'react-icons/tb'
import {
  SiDocker,
  SiDotnet,
  SiFastapi,
  SiGithub,
  SiNodedotjs,
  SiN8N,
  SiPostgresql,
  SiPython,
  SiReact,
  SiTypescript,
} from 'react-icons/si'
const technologiesData: Technology[] = [
  {
    name: 'React',
    color: '#61DAFB',
    category: 'Frontend',
    icon: SiReact,
    x: 0.10,
    y: 0.16,
    size: 'primary',
  },
  {
    name: 'Python',
    color: '#3776AB',
    category: 'Backend & IA',
    icon: SiPython,
    x: 0.90,
    y: 0.18,
    size: 'primary',
  },
  {
    name: 'Node.js',
    color: '#5FA04E',
    category: 'Backend',
    icon: SiNodedotjs,
    x: 0.94,
    y: 0.48,
    size: 'primary',
  },
  {
    name: 'FastAPI',
    color: '#009688',
    category: 'Backend',
    icon: SiFastapi,
    x: 0.84,
    y: 0.82,
    size: 'primary',
  },
  {
    name: '.NET',
    color: '#512BD4',
    category: 'Backend',
    icon: SiDotnet,
    x: 0.17,
    y: 0.83,
    size: 'primary',
  },
  {
    name: 'C#',
    color: '#9566CD',
    category: 'Backend',
    icon: TbBrandCSharp,
    x: 0.06,
    y: 0.48,
    size: 'primary',
  },

  {
    name: 'TypeScript',
    color: '#3178C6',
    category: 'Frontend',
    icon: SiTypescript,
    x: 0.31,
    y: 0.08,
    size: 'secondary',
  },
  {
    name: 'PostgreSQL',
    color: '#4169E1',
    category: 'Base de datos',
    icon: SiPostgresql,
    x: 0.69,
    y: 0.09,
    size: 'secondary',
  },
  {
    name: 'Docker',
    color: '#2496ED',
    category: 'Infraestructura',
    icon: SiDocker,
    x: 0.66,
    y: 0.91,
    size: 'secondary',
  },
  {
    name: 'n8n',
    color: '#EA4B71',
    category: 'Automatización',
    icon: SiN8N,
    x: 0.36,
    y: 0.91,
    size: 'secondary',
  },
  {
    name: 'GitHub',
    color: '#181717',
    category: 'Desarrollo',
    icon: SiGithub,
    x: 0.09,
    y: 0.69,
    size: 'secondary',
  },
  {
    name: 'Power BI',
    color: '#F2C811',
    category: 'Datos & Analytics',
    wordmark: 'PBI',
    x: 0.91,
    y: 0.69,
    size: 'secondary',
  },
  {
    name: 'SQL Server',
    category: 'Base de datos',
    color: '#CC2927',
    icon: DiMsqlServer,
    x: 0.50,
    y: 0.20,
    size: 'secondary',
  },
  {
    name: 'Power Automate',
    category: 'Automatización',
    color: '#0066FF',
    image: powerAutomateLogo,
    x: 0.50,
    y: 0.78,
    size: 'secondary',
  },
]

export { technologiesData }
